keys:
  - &charon age1mduamgqyt783gjlczg8mxa39ms90uggpay9lgqkvwun4smywzyzs3kddmc
  - &makemake age1zkkhp4henqhrwk0q2609nldgfeah3ztan5metgus3e9q8g7taa4qwg6gz8
  - &makemake-vm age16ddghh8ggkzwynz95ctf835y769jqyflsrcr8mlct8q50gtahpns50gdxy
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
    - age:
      - *charon
      - *makemake
      - *makemake-vm
