[config]
"secrets/crypt/crypt.json" = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII6uq8nXD+QBMhXqRNywwCa/dl2VVvG/2nvkw9HEPFzn p@charon",
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGdfg1ULoQiS+wRwDFU9HhZ19wS1TaAhe/QGlL/s3tE+ p@makemake",
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPwqUnE3ALTQ/ch9vv6WiE3+quklcMX3uFyMsBzKZww9 p@encke"
]
