# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/83a53e1d-034e-47e6-8bbc-3ae4ba0fde03";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4B98-BFD8";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/7c22f54a-44ba-47d9-be8e-97df8a11f30a"; }
    ];
  fileSystems."/mnt/18tb" = {
    device = "/dev/disk/by-uuid/937c61e1-9f1c-4d56-8984-5888236ab762"; 
    fsType = "xfs";
  };
  fileSystems."/mnt/4tb" = {
    device = "/dev/disk/by-uuid/7c672abf-30ec-46be-aa0f-7931d6ba1931";
    fsType = "xfs";
  };
  fileSystems."/storage" = {
    fsType = "fuse.mergerfs";
    device = "/mnt/*";
      options = ["cache.files=partial" "dropcacheonclose=true" "category.create=mfs"];
  };

  fileSystems."/data/media" = {
    device = "/storage/media/library";
    fsType = "none";
    options = [ "bind" ];
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
